<?php
// Calling template for header/footer information
require_once("inside-template.php");
$page = new Template();
$page->setTitle('Digital Collections | Archives &amp; Special Collection | Bard College');
$page->setMetaKW('');
$page->setMetaDesc('');
// print page header
$page->open();
// Exhibit Item function to repeatedly call each item.
function exhibitItem($imgURL, $imgAlt, $imgComment, $targetURL, $title, $bodyContent, $nyHeritageUsage)
{
	$nyHeritage = '<img src="https://nyheritage.org/sites/default/files/NYH_Logo_Small.png" alt="hrvh" width="100" height="39.5333" border="0" align="absmiddle" style="width: inherit !important;">';
	echo '
		<div class="exhibits-item grid-4">
			<div class="exhibits-image">
				<a href="' . $imgURL . '" target="_blank">
					<img src="' . $imgURL . '" alt="' . $imgAlt . '">
				</a>';
	if ($imgComment != '')
		echo '<p class="small-font flex-center">' . $imgComment . '</p>';
	echo '</div>
			<div class="exhibits-text">
				<h3><a target="_blank" href="' . $targetURL . '">' . $title . '</a>';
	if ($nyHeritageUsage == true)
		echo $nyHeritage;
	echo '</h3>
				<p>' . $bodyContent . '</p>
			</div>
		</div>';
}

$digitalCollData = [
	["images/digicoll/bard college arch.png", "Interior of Albee Social", "Interior of Albee Social, ca. 1935", "https://nyheritage.org/collections/bard-college-architecture-past-and-present", "Bard College Architecture, Past and Present Collection", "This collection contains photographs related to all buildings of Bard College, past and present.", true],
	["images/digicoll/bard pres coll.png", "Bard President Leon Botstein", "Bard President Leon Botstein, ca. 1980", "https://nyheritage.org/collections/bard-college-presidents", "Bard College Presidents Collection", "This collection contains photographs of the presidents of Bard College, which began as a seminary training school called St. Stephen's. During the intervening years, the administrative head of the college has variously been called Warden, Dean, and President. The title Dean was used during the years 1927-1944, when the college merged with Columbia University with President Murray Butler as head. Consecutively, these men are Warden George Franklin Seymour, 1860-1861; Warden Thomas Richey, 1861-1863; Warden Robert Brinckerhoff Fairbairn, 1863-1898; Warden Lawrence T. Cole, 1899-1903; Warden Thomas R. Harris, 1904-1907; President William Cunningham Rodgers, 1909-1919; President (later Warden and Dean) Bernard Iddings Bell, 1919-1933; Dean Donald George Tewksbury, 1933-1937; Dean Harold Mestre, 1938-1939; President Charles Harold Gray, 1940-1946; President Edward C. Fuller, 1940-1946; President James Herbert Case Jr., 1950-1960; President Reamer Kline, 1960-1974; and President Leon Botstein, 1975 to present. Two acting presidents were Robert Leigh, who served as dean under Columbia's president from 1939 to 1940, and George Bailey Hopson who served three terms as acting warden; 1898-1899, 1903-1904, and 1907-1909.", true],
	["images/digicoll/student newspaper.png", "Cover of the Bard Observer", "Cover, Bard Observer, May 8, 1968", "https://digitalcommons.bard.edu/stu_news/", "Bard College Student Newspaper Archive", "Launched in 2000 by two former Bard students, this site provides access to over 10,000 pages of student newspapers, spanning more than 100 years of Bard's history. As the creators of the site note in their introduction: 'Nowhere does one find a more intimate, personal account of Bard's cultural history than in the expressive output of the students themselves.'", false],
	["https://digitalcommons.bard.edu/assets/md5images/24a3afc0a3ed403d8656506dc1f8afd1.png", "BardCorps logo with the words BardCorops in tan with a red oval around it.", "", "http://digitalcommons.bard.edu/oral_hist/", "BardCorps-Oral Histories", "BardCorps is a collaborative oral history project of the Alumni/ae Office and the Bard College Archives. This is modeled on the famous StoryCorps initiative that travels the country recording personal stories in an Airstream trailer. We are recording the stories of Bardians to preserve memory, and to document and expand our collective understanding of Bard’s history.", false],
	["images/digicoll/john and margaret johnston bard.png", "John and Margaret Johnston Bard", "John and Margaret Johnston Bard, founders of the College.", "https://nyheritage.org/collections/bard-family-papers", "Bard Family Papers", "The letters, deeds, and other objects included here represent a small sample from a collection of Bard family materials donated to the college in 1938-39 by J.A. Sands, a Bard descendant. These selections, with dates ranging from the mid 18th through the mid 20th centuries, animate our understanding of individual family members, their relationships to each other and to the larger society.", true],
	["images/digicoll/fire engines.png", "Engines exiting the station", "Engines exiting the station, ca. 1949.", "https://nyheritage.org/collections/bard-student-fire-department", "Bard Student Fire Department Collection", "The photographs in this collection document the existence of a student-run volunteer fire department at Bard College. Initially organized in 1942, the Bard College Fire Brigade (later called simply the Bard College Fire Department) became a central campus organization when founder George Blackstone returned from military service in 1946. Intended to protect the Bard community and to provide student members with fire fighting skills, the company fought fires as far away as Rhinecliff and Clermont during its active years. As years passed, however, leadership faltered. Suffering from lack of funds and dwindling membership, <a href=\"voices/Kline-Education/kline.php\">President Kline</a> closed the department on May 3, 1960.", true],
	["images/digicoll/trinity school.png", "Trinity Church and School", "Trinity Church and School, Tivoli", "https://nyheritage.org/collections/bard-tivoli-history-collection", "Bard-Tivoli History Collection", "This collection contains photographs, letters, and other manuscript material pertaining primarily to the relationship between John and Margaret Bard and Reverend James Starr Clark. These illustrate the beginnings of St. Stephen's College in Annandale; and in Tivoli, Trinity Church and School, and Trinity Academy.", true],
	["https://blogs.bard.edu/library/files/2022/09/barrytownexplorer.png", "Barrytown Explorer on HRVH", "", "https://news.hrvh.org/veridian/?a=cl&cl=CL1&sp=idadahji&e=-------en-20--1--txt-txIN-------", "Barrytown Explorer", "The Barrytown Explorer was a local monthly newspaper published by Chanler Armstrong Chapman of Barrytown, a hamlet in the Town of Red Hook. Chapman (1901-1982) was a Livingston/Astor/Chanler family scion, a dairy farmer, a Red Hook School board member, and a witty, eccentric raconteur who delighted in flouting convention. He launched the newspaper in June 1958 during the age of the Space Race, soon after the Soviet Union had launched Sputnik, the world’s first artificial satellite, and the U.S. had successfully countered with “Explorer,” from Cape Canaveral, in Florida. The Explorer’s inaugural issue claimed “This paper is interested in four subjects. First, the Neighbors and their families; second, good schools in good Communities; third, a fair price for milk at the barn door for Dairy Farmers; Fourth, the Truth, always the truth.” The newspaper offered lively coverage of local people and events until ceasing publication in April 1982, a month after Chapman died. This collection is a collaboration with <a href=\"https://www.historicredhook.org/\" target=\"_blank\">Historic Red Hook</a> to pool our holdings of the paper and it was carefully digitized by Archives Student Workers. We worked with <a href=\"https://www.senylrc.org/\" target=\"_blank\">SENYLRC</a> to upload the combined scanned newspaper run to <a href=\"https://news.hrvh.org/veridian/?a=cl&cl=CL1&sp=idadahji&e=-------en-20--1--txt-txIN-------\" target=\"_blank\">HRVH Newspapers</a> ensuring that it is widely accessible and searchable.", false],
	["images/digicoll/bluecher.png", "Heinrich Blücher", "Heinrich Blücher", "http://www.bard.edu/bluecher/", "Blücher Archive", "Reintroduces the ideas and influence of Heinrich Blücher to the Bard community and beyond. This site features transcripts of lectures delivered in the 1950s and 1960s on the history of philosophy. These lectures embodied his ideas surrounding the Common Course, which evolved into the present First Year Seminar.", false],
	["images/digicoll/class photo.png", "St. Stephen's graduating class of 1901; Rev. George B. Hopson, seated", "St. Stephen's graduating class of 1901; Rev. George B. Hopson, seated", "https://nyheritage.org/collections/bard-class-photos", "Class Photos", "2010 marks the 150th anniversary of the founding of Bard College, formerly called St. Stephen's College. The images in this growing collection represent existing class pictures from St. Stephen's and Bard College.", true],
	["images/digicoll/chest xrays.png", "Chest x-rays at the gym, 1945.", "Chest x-rays at the gym, 1945. Professor Harvey Fite stands third in line.", "https://nyheritage.org/collections/elie-shneour-collection", "Elie Shneour Collection", "The Elie A. Shneour Collection is comprised of black and white images scanned directly from negatives found in the Bard Archives. Taken by Elie Shneour '47 during the years 1943-1948, the collection offers a snapshot of Bard during and immediately after WWII. Included are some of the first images of women at Bard, as the college became coed in 1944 causing it to break its ties with Columbia University. Other items of interest include aerial shots of the campus, theatrical and musical events, dance parties, conferences, and portraits of individuals who made Bard such a vibrant community.", true],
	["images/digicoll/hannah coll.png", "Arendt marginalia on p. 1142", "Arendt marginalia on p. 1142, in Aristotle's Graece ex Recensione Immanuelis Bekkeri", "http://www.bard.edu/arendtcollection/", "Hannah Arendt Collection, The", "This site presents images and analysis of marginalia contained in selected titles from Hannah Arendt's personal library, given to Bard after her death in 1975. It also features audio segments from 'Thinking in Dark Times,' a conference held at Bard in October of 2006 that re-examined her scholarship and commemorated the 100th anniversary of her birth.", false],
	["images/digicoll/harvey fite col.png", "Poster depicting Opus 40 for Fite sculpture xhibit held at Bard", "Poster depicting Opus 40 for Fite sculpture exhibit held at Bard 1969", "https://nyheritage.org/collections/harvey-fite-collection", "Harvey Fite Collection", "Harvey Fite was a student at St. Stephen's College until 1930. He returned as a professor, teaching classes in drama and sculpture at Bard College from 1934-1969. Many of the photos included here were given to Bard by his family in 1996 at the presentation of the self portrait sculpture which stands in the Kellogg Library. Harvey Fite was a vital force in the Bard community, and he helped to shape the college even while he worked to create the monumental landscape work which became Opus 40.", true],
	["images/digicoll/hyde park post office mural.png", "Hyde Park Post Office Mural Panel 6 featuring Drs. John and Samuel Bard", "Hyde Park Post Office Mural Panel 6 featuring Drs. John and Samuel Bard", "https://nyheritage.org/collections/olin-dows-collection", "Olin Dows Collection", "This collection contains images scanned from a series of original photographs of the work of Rhinebeck artist Olin Dows (1904-1981, b. Irvington-on-Hudson). Dows studied at Harvard University and the Yale School of Fine Arts and, significantly, spent the summer of 1929 in Mexico where he met with such luminaries as Diego Rivera and Dr. Atl. In the early-1930's, Dows became involved in Federal relief efforts for the arts through his connection to Franklin D. Roosevelt. He was appointed Director of the Treasury Relief Art Project, funded by the Works Progress Administration in 1935. This first selection highlights his work in the Rhinebeck and Hyde Park Post Offices. Dows was commissioned to paint a series of murals in the Rhinebeck Post Office in 1939, and in 1941, at the suggestion of President Roosevelt, he painted the murals in the Hyde Park Post Office as well.", true],
	["images/digicoll/paul scrapbook.png", "Page from the Paul Hartzell photo scrapbook epicting the 'Burial of the Algebra' tradition", "Page from the Paul Hartzell photo scrapbook depicting the 'Burial of the Algebra' tradition", "https://nyheritage.org/collections/paul-hartzell-album", "Paul Hartzell Album", "This photograph album was assembled by Paul Hartzell, class of 1915. It contains images of individual students, sports teams, fraternities, faculty, buildings, commencement exercises, budding romance, and various college rituals such as the Freshman Tug of War. Taken together, these provide a sense of life at St. Stephens during the years 1913-1915. <em>Images in this collection can be enlarged several times to view details.</em>", true],
	["images/digicoll/louise link.png", "Louise Link '71 stands on the Blithewood lawn.", "Louise Link '71 stands on the Blithewood lawn.", "https://nyheritage.org/collections/peter-aaron-collection", "Peter Aaron Collection", "This collection represents selected photographs of students and campus life at Bard taken by photographer Peter Aaron, '68 between the years 1964-1971. The original photographs were loaned to the archives by Mr. Aaron, scanned by Bard Archives staff, and subsequently returned to him. Included here are two aerial shots, some posed portraits, and a variety of candid images of students hanging out and having fun. Dark glasses and sideburns notwithstanding, together they offer a snapshot of Bard in the 1960s that, in many instances, might have been taken yesterday.", true],
	["https://digitalcommons.bard.edu/poetry_at_bard/1000/thumbnail.jpg", "Poetry at Bard digital commons thumbnail.", "", "https://digitalcommons.bard.edu/poetry_at_bard/index.html", "Poetry at Bard", "These audio recordings have been digitized from a collection of cassette and open reel tapes of readings and lectures at Bard over the last 50 years. The collection was initially established with funds provided by the Carter A Towbin Poetry Fund in 1982 and first located in Albee Hall before moving to the Olin Building. Our hope is to use the recordings to help tell the story of Bard as an exuberant place for poetry for more than half a century.", false],
	["images/digicoll/tennis team.png", "St. Stephen's freshmen tennis team", "St. Stephen's freshmen tennis team, 1923", "https://nyheritage.org/collections/sports-st-stephens", "Sports at St. Stephen's", "Athletics thrived at St. Stephen's beginning in the 1920s with many teams achieving national rankings in their respective sports. Under the energetic leadership of Bernard Iddings Bell, construction on the Memorial Gymnasium was completed in 1921, a new athletic director was hired, and by 1925 a proper athletic field was completed next to the Hoffman Library. Sports teams, or 'squads' were often generically referred to as the 'Saints,' but individual teams were affectionately referred to as the 'Scarlet Harriers' (cross country); the 'Scarlet Bootmen' (soccer); the 'Scarlet Stickmen' (lacross); the 'Scarlet Icemen,' or 'Scarlet Rinkmen' (hockey); the 'Red and White' (basketball); and the 'Crimson and White'(football). Tennis, Rugby and Bowling were also popular. While the drama of those games has evaporated, these team images retain and reflect the spark and prowess of the athletes of the day.", true],
	["images/digicoll/tivoli coll.png", "Dolly Freeborn driving car on Friendship St.", "Dolly Freeborn driving car on Friendship St., Tivoli", "https://nyheritage.org/collections/tivoli-collection", "Tivoli Collection", "The Tivoli Collection is comprised of selected photographs of Tivoli collected by the late Joan Navins, former Village Historian.", true],
	["images/digicoll/roosevelt.png", "Eleanor Roosevelt with William Matthews at Ward Manor", "Eleanor Roosevelt with William Matthews at Ward Manor 1938 David Wordell Collection", "https://nyheritage.org/collections/ward-manor", "Ward Manor Collection", "In 1926 William Ward of the Ward Baking Company funded the renovation of the river estate known as Almonte for purposes of creating a home for the elderly in the 'gray manor house', to be managed and run by his friend William Matthews. Soon, Matthews extended the operation to include summer camps for girls and boys, and summer bungalow rentals to poor families in some 56 buildings extending from Cruger's Island, through what is now Tivoli Bays, to the \"Homestead\" mansion at the southern edge of the village of Tivoli. This photograph collection, owned by William Matthews' grandaughter Donna Matthews, documents these activities and the lives that were led here for more than 30 years. Very few of these buildings are standing today.", true],
	["images/digicoll/radio station.png", "Weekly variety show of WXBC broadcast", "Weekly variety show of WXBC broadcast, spring 1950.", "https://nyheritage.org/collections/bard-college-radio-wxbc", "WXBC Collection", "WXBC was envisioned in 1946 by Elie Shneour '47, and implemented by many hands, including those of John Gillin '47 who wrote his senior project about the technical design and construction of this college radio station. The 'X' in its call letters stood for \"Experimental,\" and the 1951 yearbook described the station as the \"Voice of the Bard Campus.\" The photographs in this collection record some of the events of WXBC in its early years.", true],
];
?>

<div class="right-content inside-page digital-collection">
	<div class="important-info content-item">
		<h2>Digital Collections</h2>
		<div>
			<p class="italic">
				The digital collections found here have all been created at Bard, and several of these collections - the Hannah Arendt Collection, the Blücher Archive, and the Student Newspaper Archive - are hosted at Bard as well. Other collections are hosted by <a target="_blank" href="https://nyheritage.org/contributors/bard-college-archives-and-special-collections" target="_blank">New York Heritage</a>.
			</p>

			<?php
			for ($x = 0; $x < count($digitalCollData); $x++)
				exhibitItem($digitalCollData[$x][0], $digitalCollData[$x][1], $digitalCollData[$x][2], $digitalCollData[$x][3], $digitalCollData[$x][4], $digitalCollData[$x][5], $digitalCollData[$x][6]);
			?>

			<p>Rights and Usage Information for Bard College Archives and Special Collections Digital Collections: The materials on this web site are made available for use in research, teaching and private study. For those purposes the user may reproduce these materials (by download, printing, etc.) without further permission, on the condition that proper attribution of the source for all copies is provided by clearly acknowledging the name of the Library, the title of the web page or resource, and the URL at which it was located. </p>

			<p>For other uses of these materials, i.e. in commercial products, for broadcast or publication, permission must be obtained in advance from the Bard College Archives and Special Collections staff. </p>
		</div>
	</div>
</div>
<?php
// Printing footer
$page->close();
?>
